server:
  port: 8080

spring:
  application:
    name: backend

  profiles:
    active: local

  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

  jwt:
    secret: ${JWT_SECRET:sthing-secret-key-must-be-at-least-256-bits-long!!}
    expiration: 86400000  # 24시간 (ms)